apiVersion: v1
kind: Pod
metadata:
  name: {{APP_NAME}}
  namespace: {{K8S_NAMESPACE}}
spec:
  containers:
    - name: {{APP_NAME}}
      image: {{IMAGE_NAME}}
      imagePullPolicy: Always
      ports:
        - containerPort: 8000
